server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect    
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
    consumer:
      group-id: ms_mail_consumer
  mail:
    host: mail.isaiaslopezti.com 
    port: 26
    username: info@isaiaslopezti.com 
    password: Prueba@2020*
    properties.mail.smtp:
      auth: true
      # starttls.enable: true
security:
  basic:
    enabled: false    
